// GENERATED by gen_party.py (Perfect UI party screen) - layout of the new slot art
#ifndef GUARD_PERFECT_PARTY_UI_H
#define GUARD_PERFECT_PARTY_UI_H
#define PERFECT_PARTY_PATTERN_TILE 15   // plain background tile (under the cancel button in the showcase)
#define PERFECT_MAIN_BAR_X 30
#define PERFECT_MAIN_BAR_Y 31
#define PERFECT_MAIN_BAR_W 45
#define PERFECT_WIDE_BAR_X 86
#define PERFECT_WIDE_BAR_Y 9
#define PERFECT_WIDE_BAR_W 52
#endif
