// GENERATED by gen_grassy.py (v6.0): grass metatiles - no rain reflections on them in towns and cities
#include "global.h"
#include "fieldmap.h"
extern const u16 gMetatiles_General[];
extern const u16 gMetatiles_Petalburg[];
extern const u16 gMetatiles_Rustboro[];
extern const u16 gMetatiles_Dewford[];
extern const u16 gMetatiles_Slateport[];
extern const u16 gMetatiles_Mauville[];
extern const u16 gMetatiles_Lavaridge[];
extern const u16 gMetatiles_Fallarbor[];
extern const u16 gMetatiles_Fortree[];
extern const u16 gMetatiles_Lilycove[];
extern const u16 gMetatiles_Mossdeep[];
extern const u16 gMetatiles_EverGrande[];
extern const u16 gMetatiles_Pacifidlog[];
extern const u16 gMetatiles_Sootopolis[];
extern const u16 gMetatiles_BattleFrontierOutsideWest[];
extern const u16 gMetatiles_BattleFrontierOutsideEast[];
extern const u16 gMetatiles_Shop[];
extern const u16 gMetatiles_PokemonCenter[];
extern const u16 gMetatiles_Cave[];
extern const u16 gMetatiles_PokemonSchool[];
extern const u16 gMetatiles_PokemonFanClub[];
extern const u16 gMetatiles_Unused1[];
extern const u16 gMetatiles_MeteorFalls[];
extern const u16 gMetatiles_OceanicMuseum[];
extern const u16 gMetatiles_CableClub[];
extern const u16 gMetatiles_SeashoreHouse[];
extern const u16 gMetatiles_PrettyPetalFlowerShop[];
extern const u16 gMetatiles_PokemonDayCare[];
extern const u16 gMetatiles_Facility[];
extern const u16 gMetatiles_BikeShop[];
extern const u16 gMetatiles_RusturfTunnel[];
extern const u16 gMetatiles_InsideOfTruck[];
extern const u16 gMetatiles_Contest[];
extern const u16 gMetatiles_LilycoveMuseum[];
extern const u16 gMetatiles_BrendansMaysHouse[];
extern const u16 gMetatiles_Lab[];
extern const u16 gMetatiles_Underwater[];
extern const u16 gMetatiles_GenericBuilding[];
extern const u16 gMetatiles_MauvilleGameCorner[];
extern const u16 gMetatiles_Unused2[];
extern const u16 gMetatiles_RustboroGym[];
extern const u16 gMetatiles_DewfordGym[];
extern const u16 gMetatiles_MauvilleGym[];
extern const u16 gMetatiles_LavaridgeGym[];
extern const u16 gMetatiles_PetalburgGym[];
extern const u16 gMetatiles_FortreeGym[];
extern const u16 gMetatiles_MossdeepGym[];
extern const u16 gMetatiles_SootopolisGym[];
extern const u16 gMetatiles_TrickHousePuzzle[];
extern const u16 gMetatiles_InsideShip[];
extern const u16 gMetatiles_EliteFour[];
extern const u16 gMetatiles_BattleFrontier[];
extern const u16 gMetatiles_BattlePalace[];
extern const u16 gMetatiles_BattleDome[];
extern const u16 gMetatiles_BattleFactory[];
extern const u16 gMetatiles_BattlePike[];
extern const u16 gMetatiles_BattleArena[];
extern const u16 gMetatiles_BattlePyramid[];
extern const u16 gMetatiles_MirageTower[];
extern const u16 gMetatiles_MossdeepGameCorner[];
extern const u16 gMetatiles_IslandHarbor[];
extern const u16 gMetatiles_TrainerHill[];
extern const u16 gMetatiles_NavelRock[];
extern const u16 gMetatiles_BattleFrontierRankingHall[];
extern const u16 gMetatiles_BattleTent[];
extern const u16 gMetatiles_MysteryEventsHouse[];
extern const u16 gMetatiles_UnionRoom[];
static const u8 sGrassy_General[64] = {150,231,229,253,245,203,201,64,233,79,9,9,9,199,5,5,248,120,0,0,0,0,0,0,192,0,120,128,153,0,64,192,248,40,56,0,0,0,63,7,7,47,0,0,0,0,0,0,136,24,0,2,4,28,92,31,255,255,7,7,15,15,0,3};
static const u8 sGrassy_Petalburg[64] = {254,119,7,80,95,15,0,240,124,16,19,32,243,115,119,127,92,83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Rustboro[64] = {248,0,0,0,0,0,0,0,0,63,0,5,0,31,0,0,193,63,0,0,0,0,128,0,2,0,192,224,224,32,160,224,192,192,192,16,140,8,135,216,0,0,0,0,124,28,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Dewford[64] = {134,0,0,0,0,4,0,0,0,1,1,1,138,174,130,112,0,0,243,232,235,107,3,129,1,193,196,112,176,176,48,0,0,1,0,0,0,248,255,255,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Slateport[64] = {0,0,0,0,7,23,0,0,15,199,223,209,255,224,31,7,7,7,239,31,31,31,255,0,15,15,31,0,0,0,0,16,151,224,255,255,255,31,63,0,0,0,0,0,0,0,62,62,62,62,62,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Mauville[64] = {242,255,255,127,127,127,224,0,208,0,0,0,142,128,140,220,255,253,255,255,231,162,166,14,31,63,7,31,31,27,0,0,0,0,0,15,11,0,0,0,0,112,159,255,159,255,255,255,191,95,31,15,31,0,3,124,124,124,124,0,0,0,0,7};
static const u8 sGrassy_Lavaridge[64] = {70,2,0,192,0,0,0,0,0,5,0,0,200,56,40,0,31,29,7,0,224,32,33,1,0,0,0,0,0,96,112,15,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Fallarbor[64] = {0,0,4,0,0,0,0,7,5,5,0,0,0,128,0,8,8,16,0,16,0,0,0,0,0,0,7,5,7,0,0,0,0,0,0,0,0,16,19,255,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Fortree[64] = {62,51,24,24,0,119,5,2,0,248,186,239,63,7,71,79,14,7,7,31,0,9,127,119,119,119,119,1,79,71,7,7,7,195,194,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Lilycove[64] = {128,1,0,0,18,224,224,224,248,254,255,7,8,1,7,122,3,28,60,44,12,8,96,0,7,103,231,223,127,255,191,247,223,255,235,253,186,247,47,239,31,255,223,107,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Mossdeep[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,63,207,128,128,192,129,196,196,252,252,220,0,28,255,156,28,204,204,248,248,0,0,0,120,24,127,127,0,0,0,0,126,126,255,255,255,63,63,0,0,0,0,0,0,0};
static const u8 sGrassy_EverGrande[64] = {248,0,0,1,255,252,252,252,2,177,177,177,215,245,255,119,7,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Pacifidlog[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Sootopolis[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,28,0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattleFrontierOutsideWest[64] = {62,0,2,0,7,128,0,0,0,0,9,0,0,0,0,124,247,243,243,243,227,243,255,255,255,255,40,239,102,111,127,127,95,31,0,0,0,0,0,0,0,0,0,0,0,128,128,252,252,252,180,0,0,248,255,243,49,17,49,31,31,27,27,11};
static const u8 sGrassy_BattleFrontierOutsideEast[64] = {126,255,255,143,255,255,143,167,7,7,7,7,63,31,31,31,0,0,0,0,0,0,128,130,128,144,248,249,127,255,15,127,127,253,253,250,2,2,0,0,56,197,237,40,15,231,239,255,255,247,180,56,0,192,0,0,0,0,160,0,0,3,17,8};
static const u8 sGrassy_Shop[64] = {254,255,16,80,35,59,31,31,15,0,0,0,0,32,96,0,12,0,192,72,128,207,140,8,224,0,1,32,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_PokemonCenter[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Cave[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_PokemonSchool[64] = {0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_PokemonFanClub[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Unused1[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_MeteorFalls[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_OceanicMuseum[64] = {2,0,3,0,31,0,0,24,0,0,31,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_CableClub[64] = {0,0,0,0,133,132,0,0,0,0,0,0,0,124,16,0,0,0,0,32,246,6,6,0,128,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_SeashoreHouse[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_PrettyPetalFlowerShop[64] = {0,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_PokemonDayCare[64] = {16,0,0,4,0,38,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Facility[64] = {60,57,252,162,224,134,128,127,127,255,103,101,121,31,195,195,240,252,159,24,127,28,195,192,199,0,0,0,0,0,0,0,0,0,0,0,48,252,172,255,17,240,16,231,0,0,0,248,0,0,0,0,0,0,48,0,0,30,0,48,69,75,59,35};
static const u8 sGrassy_BikeShop[64] = {64,64,254,91,123,128,0,31,129,4,6,0,192,32,32,162,64,0,0,0,0,126,32,255,255,240,0,192,64,209,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_RusturfTunnel[64] = {254,255,239,255,255,31,31,31,31,15,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_InsideOfTruck[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Contest[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,186,135,186,130,186,190,190,134,190,130,186,128,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_LilycoveMuseum[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,244,244,0,119,71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BrendansMaysHouse[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Lab[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Underwater[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_GenericBuilding[64] = {0,0,3,0,2,2,0,0,17,192,192,130,0,0,0,0,0,0,0,0,0,63,216,0,7,192,64,0,0,0,24,224,192,192,48,6,132,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_MauvilleGameCorner[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_Unused2[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_RustboroGym[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_DewfordGym[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_MauvilleGym[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_LavaridgeGym[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_PetalburgGym[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_FortreeGym[64] = {0,128,0,2,65,18,0,0,0,128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_MossdeepGym[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_SootopolisGym[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_TrickHousePuzzle[64] = {0,1,249,63,64,0,0,219,228,27,191,183,0,0,31,193,192,0,0,16,16,16,16,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_InsideShip[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_EliteFour[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattleFrontier[64] = {0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,224,0,0,0,31,31,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattlePalace[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattleDome[64] = {136,136,128,128,0,16,0,0,1,1,1,0,200,200,194,224,254,56,3,3,227,7,255,29,0,1,0,248,13,4,0,0,22,28,48,32,128,128,104,56,31,3,112,0,7,7,126,126,254,31,127,127,3,7,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattleFactory[64] = {0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattlePike[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattleArena[64] = {0,0,0,0,0,255,255,255,255,255,0,0,0,6,0,192,0,0,32,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattlePyramid[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_MirageTower[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_MossdeepGameCorner[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_IslandHarbor[64] = {12,1,1,223,71,125,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35,32,32,0,111,46,62,0,0,0,0,0};
static const u8 sGrassy_TrainerHill[64] = {0,0,0,0,255,255,191,255,80,32,168,255,255,191,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,156,3,80,192,46,126,69,181,181,0,248,0,0,0,0,0,33,55,71,87,59,56,58,179,31,51,0,0,0,0,0,0};
static const u8 sGrassy_NavelRock[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattleFrontierRankingHall[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_BattleTent[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_MysteryEventsHouse[64] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const u8 sGrassy_UnionRoom[64] = {224,224,255,247,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const struct { const u16 *metatiles; const u8 *grassy; } sGrassyTables[] = {
    {gMetatiles_General, sGrassy_General},
    {gMetatiles_Petalburg, sGrassy_Petalburg},
    {gMetatiles_Rustboro, sGrassy_Rustboro},
    {gMetatiles_Dewford, sGrassy_Dewford},
    {gMetatiles_Slateport, sGrassy_Slateport},
    {gMetatiles_Mauville, sGrassy_Mauville},
    {gMetatiles_Lavaridge, sGrassy_Lavaridge},
    {gMetatiles_Fallarbor, sGrassy_Fallarbor},
    {gMetatiles_Fortree, sGrassy_Fortree},
    {gMetatiles_Lilycove, sGrassy_Lilycove},
    {gMetatiles_Mossdeep, sGrassy_Mossdeep},
    {gMetatiles_EverGrande, sGrassy_EverGrande},
    {gMetatiles_Pacifidlog, sGrassy_Pacifidlog},
    {gMetatiles_Sootopolis, sGrassy_Sootopolis},
    {gMetatiles_BattleFrontierOutsideWest, sGrassy_BattleFrontierOutsideWest},
    {gMetatiles_BattleFrontierOutsideEast, sGrassy_BattleFrontierOutsideEast},
    {gMetatiles_Shop, sGrassy_Shop},
    {gMetatiles_PokemonCenter, sGrassy_PokemonCenter},
    {gMetatiles_Cave, sGrassy_Cave},
    {gMetatiles_PokemonSchool, sGrassy_PokemonSchool},
    {gMetatiles_PokemonFanClub, sGrassy_PokemonFanClub},
    {gMetatiles_Unused1, sGrassy_Unused1},
    {gMetatiles_MeteorFalls, sGrassy_MeteorFalls},
    {gMetatiles_OceanicMuseum, sGrassy_OceanicMuseum},
    {gMetatiles_CableClub, sGrassy_CableClub},
    {gMetatiles_SeashoreHouse, sGrassy_SeashoreHouse},
    {gMetatiles_PrettyPetalFlowerShop, sGrassy_PrettyPetalFlowerShop},
    {gMetatiles_PokemonDayCare, sGrassy_PokemonDayCare},
    {gMetatiles_Facility, sGrassy_Facility},
    {gMetatiles_BikeShop, sGrassy_BikeShop},
    {gMetatiles_RusturfTunnel, sGrassy_RusturfTunnel},
    {gMetatiles_InsideOfTruck, sGrassy_InsideOfTruck},
    {gMetatiles_Contest, sGrassy_Contest},
    {gMetatiles_LilycoveMuseum, sGrassy_LilycoveMuseum},
    {gMetatiles_BrendansMaysHouse, sGrassy_BrendansMaysHouse},
    {gMetatiles_Lab, sGrassy_Lab},
    {gMetatiles_Underwater, sGrassy_Underwater},
    {gMetatiles_GenericBuilding, sGrassy_GenericBuilding},
    {gMetatiles_MauvilleGameCorner, sGrassy_MauvilleGameCorner},
    {gMetatiles_Unused2, sGrassy_Unused2},
    {gMetatiles_RustboroGym, sGrassy_RustboroGym},
    {gMetatiles_DewfordGym, sGrassy_DewfordGym},
    {gMetatiles_MauvilleGym, sGrassy_MauvilleGym},
    {gMetatiles_LavaridgeGym, sGrassy_LavaridgeGym},
    {gMetatiles_PetalburgGym, sGrassy_PetalburgGym},
    {gMetatiles_FortreeGym, sGrassy_FortreeGym},
    {gMetatiles_MossdeepGym, sGrassy_MossdeepGym},
    {gMetatiles_SootopolisGym, sGrassy_SootopolisGym},
    {gMetatiles_TrickHousePuzzle, sGrassy_TrickHousePuzzle},
    {gMetatiles_InsideShip, sGrassy_InsideShip},
    {gMetatiles_EliteFour, sGrassy_EliteFour},
    {gMetatiles_BattleFrontier, sGrassy_BattleFrontier},
    {gMetatiles_BattlePalace, sGrassy_BattlePalace},
    {gMetatiles_BattleDome, sGrassy_BattleDome},
    {gMetatiles_BattleFactory, sGrassy_BattleFactory},
    {gMetatiles_BattlePike, sGrassy_BattlePike},
    {gMetatiles_BattleArena, sGrassy_BattleArena},
    {gMetatiles_BattlePyramid, sGrassy_BattlePyramid},
    {gMetatiles_MirageTower, sGrassy_MirageTower},
    {gMetatiles_MossdeepGameCorner, sGrassy_MossdeepGameCorner},
    {gMetatiles_IslandHarbor, sGrassy_IslandHarbor},
    {gMetatiles_TrainerHill, sGrassy_TrainerHill},
    {gMetatiles_NavelRock, sGrassy_NavelRock},
    {gMetatiles_BattleFrontierRankingHall, sGrassy_BattleFrontierRankingHall},
    {gMetatiles_BattleTent, sGrassy_BattleTent},
    {gMetatiles_MysteryEventsHouse, sGrassy_MysteryEventsHouse},
    {gMetatiles_UnionRoom, sGrassy_UnionRoom},
};
